PHYSICAL_READ_TIME_INTERVAL = 5
CAM_READ_TIME_INTERVAL = 4
NUMBER_OF_DATAPOINTS = 6

#NUMBER_OF_PREDICTION_DATA should be > NUMBER_OF_DATAPOINTS
# NUMBER_OF_PREDICTION_DATA should be > 70 for 
# the ARMA model to not complain
NUMBER_FOR_PREDICTION_DATA = 20
NUMBER_FOR_PREDICTION_AQI = 20

CO_THRESHOLD = 60
TEM_THRESHOLD = 60

VALIDATING_THRESHOLD = {
    "temperature" : 25,
    "humidity" : 25,
    "co" : 15,
    "co2": 15,
    "so2": 15,
    "no2": 15,
    "pm2_5": 15,
    "pm10": 15 
}
