PHYSICAL_READ_TIME_INTERVAL = 10 
NUMBER_OF_DATAPOINTS = 6

#NUMBER_OF_PREDICTION_DATA should be greater than NUMBER_OF_DATAPOINTS
NUMBER_OF_PREDICTION_DATA = 20

CO_THRESHOLD = 60
TEM_THRESHOLD = 60

VALIDATING_THRESHOLD = 10
