PHYSICAL_READ_TIME_INTERVAL = 30 
NUMBER_OF_DATAPOINTS = 10

#NUMBER_OF_PREDICTION_DATA should be greater than NUMBER_OF_DATAPOINTS
NUMBER_OF_PREDICTION_DATA = 10

CO_THRESHOLD = 60
TEM_THRESHOLD = 60

VALIDATING_THRESHOLD = 10
